version: "3.8"
services:
  mongo42:
    image: mongo:4.2
    container_name: mongoup-mongo42
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "30000:27017"
    expose:
      - "30000"
